Develop
RaphaFang/Taipei-day-trip--DONE pull request #8
Opened 2024-07-03 13:18 UTC by RaphaFang

老師您好：
我是學生方思渝，以下是本週作業連結

https://raphaelfang.com/

2024-07-03 16:45 UTC, cwpeng requested changes
We should redirect user to the booking page after booking.

2024-07-04 00:38 UTC, RaphaFang commented
老師您好

已經修正此錯誤，並重新導向 -> /booking

2024-07-04 05:27 UTC, cwpeng requested changes
The same issue.

2024-07-04 06:11 UTC, RaphaFang commented
老師您好
已修正問題，再麻煩老師檢查一次

2024-07-04 10:03 UTC, cwpeng approved these changes
OK. Done.

2024-07-04 10:48 UTC, merged